services:
  redis:
    image: redis/redis-stack:${REDIS_VERSION:-latest}
    env_file:
      - .env
    volumes:
      - ./redis-data:/data
      - ./redis-stack.conf:/redis-stack.conf
      - ./entrypoint.sh:/entrypoint.sh
    ports:
      - "${REDIS_EXTERNAL_PORT:-6379}:6379"
    command: "sh /entrypoint.sh"
    deploy:
      placement:
        constraints:
          - node.labels.role == redis-storage
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "redis-cli --no-auth-warning -a ${REDIS_PASSWORD} ping | grep PONG"]
      interval: 30s
      timeout: 20s
      retries: 3