services:
  redis:
    image: ${IMAGE_NAME:-redis/redis-stack:latest}
    volumes:
      - redis-data:/data
    ports:
      - "${REDIS_EXTERNAL_PORT:-6379}:6379"
    command: "sh /entrypoint.sh"
    environment:
      - IMAGE_NAME=${IMAGE_NAME}
      - CONTAINER_NAME=${CONTAINER_NAME}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_EXTERNAL_PORT=${REDIS_EXTERNAL_PORT}
      - REDIS_REPLICAS=${REDIS_REPLICAS}
      - REDIS_VERSION=${REDIS_VERSION}
    deploy:
      mode: replicated
      replicas: ${REDIS_REPLICAS:-1}
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    healthcheck:
      test: "redis-cli --no-auth-warning -a ${REDIS_PASSWORD} ping | grep PONG"
      interval: 30s
      timeout: 20s
      retries: 3


volumes:
  redis-data:
    driver: local
