services:
  redis:
    image: redis/redis-stack:${REDIS_VERSION:-latest}
    container_name: ${CONTAINER_NAME:-redis_stack}
    env_file:
      - ./.env
    volumes:
      - ./redis-data:/data
      - './redis-stack.conf:/redis-stack.conf'
      - './entrypoint.sh:/entrypoint.sh'
    ports:
      - "${REDIS_EXTERNAL_PORT:-6379}:6379"
    command: "sh /entrypoint.sh"
    restart: always
    healthcheck:
      test: "redis-cli --no-auth-warning -a ${REDIS_PASSWORD} ping | grep PONG"
      interval: 30s
      timeout: 20s
      retries: 3
